[package]
name = "rust-utils"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.99"
fs_extra = "1.3.0"
walkdir = "2.5.0"
zip = "4.3.0"
