// optifine settings (DON'T DELETE)
/*
const int   colortex0Format       = RGB10_A2;
const bool  colortex0Clear        = false;
const int   colortex1Format       = RGB10_A2;
const bool  colortex1Clear        = false;
const int   colortex2Format       = RGB16;
const bool  colortex2Clear        = false;
const int   colortex3Format       = RGB16;
const bool  colortex3Clear        = true;
const int   colortex4Format       = RGB10_A2;
const bool  colortex4Clear        = false;
const int   colortex5Format       = RGB10_A2;
const bool  colortex5Clear        = true;
const int   colortex6Format       = RG16;
const bool  colortex6Clear        = false;
const bool  shadowtex0Clear       = false;
const bool  shadowtex1Clear       = false;
const float wetnessHalflife       = 50.0f;
const float drynessHalflife       = 50.0f;
const float centerDepthHalflife   = 2.5f;
const float eyeBrightnessHalflife = 4.0f;
const float ambientOcclusionLevel = 1.0;
const float shadowIntervalSize    = 2.0;
*/





// settings basics

#include "/setting_defines.glsl"

#if STYLE == 0
	#include "/style_vanilla.glsl"
#endif
#if STYLE == 1
	#include "/style_fantasy.glsl"
#endif
#if STYLE == 2
	#include "/style_realistic.glsl"
#endif
#if STYLE == 3
	#include "/style_cartoon.glsl"
#endif





// post-processed definitions



#ifdef NETHER
	#undef SHADOWS_ENABLED
	#define SHADOWS_ENABLED 0
	#undef DEPTH_SUNRAYS_ENABLED
	#define DEPTH_SUNRAYS_ENABLED 0
	#undef VOL_SUNRAYS_ENABLED
	#define VOL_SUNRAYS_ENABLED 0
#endif

#ifdef END
	#undef DEPTH_SUNRAYS_ENABLED
	#define DEPTH_SUNRAYS_ENABLED 0
	#undef VOL_SUNRAYS_ENABLED
	#define VOL_SUNRAYS_ENABLED 0
#endif

#if SHADOWS_ENABLED == 0
	#undef VOL_SUNRAYS_ENABLED
	#define VOL_SUNRAYS_ENABLED 0
#endif

#if KUWAHARA_ENABLED == 1
	#undef SHARPENING_ENABLED
	#define SHARPENING_ENABLED 0
#endif

#ifdef DISTANT_HORIZONS
	#undef BORDER_FOG_ENABLED
	#define BORDER_FOG_ENABLED 0
#endif



#if SSS_PIXELS != 0
	#undef TAA_ENABLED
	#defined TAA_ENABLED 0
	#undef FXAA_ENABLED
	#defined FXAA_ENABLED 0
	#undef SHARPENING_ENABLED
	#defined SHARPENING_ENABLED 0
#endif



#if TEMPORAL_FILTER_ENABLED == 0
	#undef TAA_ENABLED
	#define TAA_ENABLED 0
#endif



// How on earth can optifine be THIS bad???
#if TEMPORAL_FILTER_ENABLED == 1
	#undef TEMPORAL_FILTER_ENABLED
	#define TEMPORAL_FILTER_ENABLED 1
#endif
#if SSS_PHOSPHOR == 1
	#undef SSS_PHOSPHOR
	#define SSS_PHOSPHOR 1
#endif
#if MOTION_BLUR_ENABLED == 1
	#undef MOTION_BLUR_ENABLED
	#define MOTION_BLUR_ENABLED 1
#endif



#define BLOCK_COLOR vec3(BLOCK_RED, BLOCK_GREEN, BLOCK_BLUE) * BLOCK_BRIGHTNESS
#define CAVE_AMBIENT_COLOR vec3(CAVE_AMBIENT_RED, CAVE_AMBIENT_GREEN, CAVE_AMBIENT_BLUE) * CAVE_AMBIENT_BRIGHTNESS
#define NETHER_AMBIENT_COLOR vec3(NETHER_AMBIENT_RED, NETHER_AMBIENT_GREEN, NETHER_AMBIENT_BLUE) * NETHER_AMBIENT_BRIGHTNESS;
#define NETHER_BLOCKLIGHT_MULT vec3(NETHER_BLOCKLIGHT_RED_MULT, NETHER_BLOCKLIGHT_GREEN_MULT, NETHER_BLOCKLIGHT_BLUE_MULT) * NETHER_BLOCKLIGHT_BRIGHTNESS_MULT
#define END_SKYLIGHT_COLOR vec3(END_SKYLIGHT_RED, END_SKYLIGHT_GREEN, END_SKYLIGHT_BLUE) * END_SKYLIGHT_BRIGHTNESS
#define END_AMBIENT_COLOR vec3(END_AMBIENT_RED, END_AMBIENT_GREEN, END_AMBIENT_BLUE) * END_AMBIENT_BRIGHTNESS
#define WATER_COLOR vec3(WATER_COLOR_RED, WATER_COLOR_GREEN, WATER_COLOR_BLUE)

#define SKYLIGHT_DAY_COLOR vec3(SKYLIGHT_DAY_RED, SKYLIGHT_DAY_GREEN, SKYLIGHT_DAY_BLUE) * SKYLIGHT_DAY_BRIGHTNESS
#define AMBIENT_DAY_COLOR vec3(AMBIENT_DAY_RED, AMBIENT_DAY_GREEN, AMBIENT_DAY_BLUE) * AMBIENT_DAY_BRIGHTNESS

#define SKYLIGHT_NIGHT_COLOR vec3(SKYLIGHT_NIGHT_RED, SKYLIGHT_NIGHT_GREEN, SKYLIGHT_NIGHT_BLUE) * SKYLIGHT_NIGHT_BRIGHTNESS
#define AMBIENT_NIGHT_COLOR vec3(AMBIENT_NIGHT_RED, AMBIENT_NIGHT_GREEN, AMBIENT_NIGHT_BLUE) * AMBIENT_NIGHT_BRIGHTNESS

#define SKYLIGHT_SUNRISE_COLOR vec3(SKYLIGHT_SUNRISE_RED, SKYLIGHT_SUNRISE_GREEN, SKYLIGHT_SUNRISE_BLUE) * SKYLIGHT_SUNRISE_BRIGHTNESS
#define AMBIENT_SUNRISE_COLOR vec3(AMBIENT_SUNRISE_RED, AMBIENT_SUNRISE_GREEN, AMBIENT_SUNRISE_BLUE) * AMBIENT_SUNRISE_BRIGHTNESS

#define SKYLIGHT_SUNSET_COLOR vec3(SKYLIGHT_SUNSET_RED, SKYLIGHT_SUNSET_GREEN, SKYLIGHT_SUNSET_BLUE) * SKYLIGHT_SUNSET_BRIGHTNESS
#define AMBIENT_SUNSET_COLOR vec3(AMBIENT_SUNSET_RED, AMBIENT_SUNSET_GREEN, AMBIENT_SUNSET_BLUE) * AMBIENT_SUNSET_BRIGHTNESS

#define ATMOSPHERIC_FOG_DAY vec3(ATMOSPHERIC_FOG_DAY_RED, ATMOSPHERIC_FOG_DAY_GREEN, ATMOSPHERIC_FOG_DAY_BLUE)
#define ATMOSPHERIC_FOG_NIGHT vec3(ATMOSPHERIC_FOG_NIGHT_RED, ATMOSPHERIC_FOG_NIGHT_GREEN, ATMOSPHERIC_FOG_NIGHT_BLUE)
#define ATMOSPHERIC_FOG_SUNRISE vec3(ATMOSPHERIC_FOG_SUNRISE_RED, ATMOSPHERIC_FOG_SUNRISE_GREEN, ATMOSPHERIC_FOG_SUNRISE_BLUE)
#define ATMOSPHERIC_FOG_SUNSET vec3(ATMOSPHERIC_FOG_SUNSET_RED, ATMOSPHERIC_FOG_SUNSET_GREEN, ATMOSPHERIC_FOG_SUNSET_BLUE)

#define SUNRAYS_SUN_COLOR vec3(SUNRAYS_SUN_RED, SUNRAYS_SUN_GREEN, SUNRAYS_SUN_BLUE)
#define SUNRAYS_MOON_COLOR vec3(SUNRAYS_MOON_RED, SUNRAYS_MOON_GREEN, SUNRAYS_MOON_BLUE)

#define SKY_DAY_COLOR vec3(SKY_DAY_RED, SKY_DAY_GREEN, SKY_DAY_BLUE)
#define SKY_NIGHT_COLOR vec3(SKY_NIGHT_RED, SKY_NIGHT_GREEN, SKY_NIGHT_BLUE)
#define SKY_HORIZON_DAY_COLOR vec3(SKY_HORIZON_DAY_RED, SKY_HORIZON_DAY_GREEN, SKY_HORIZON_DAY_BLUE)
#define SKY_HORIZON_NIGHT_COLOR vec3(SKY_HORIZON_NIGHT_RED, SKY_HORIZON_NIGHT_GREEN, SKY_HORIZON_NIGHT_BLUE)
#define SKY_HORIZON_SUNRISE_COLOR vec3(SKY_HORIZON_SUNRISE_RED, SKY_HORIZON_SUNRISE_GREEN, SKY_HORIZON_SUNRISE_BLUE)
#define SKY_HORIZON_SUNSET_COLOR vec3(SKY_HORIZON_SUNSET_RED, SKY_HORIZON_SUNSET_GREEN, SKY_HORIZON_SUNSET_BLUE)

#define CLOUD_DAY_COLOR vec3(CLOUD_DAY_RED, CLOUD_DAY_GREEN, CLOUD_DAY_BLUE)
#define CLOUD_NIGHT_COLOR vec3(CLOUD_NIGHT_RED, CLOUD_NIGHT_GREEN, CLOUD_NIGHT_BLUE)
#define CLOUD_SUNRISE_COLOR vec3(CLOUD_SUNRISE_RED, CLOUD_SUNRISE_GREEN, CLOUD_SUNRISE_BLUE)
#define CLOUD_SUNSET_COLOR vec3(CLOUD_SUNSET_RED, CLOUD_SUNSET_GREEN, CLOUD_SUNSET_BLUE)

#define IN_WATER_COLOR vec3(IN_WATER_RED, IN_WATER_GREEN, IN_WATER_BLUE)
#define IN_LAVA_COLOR vec3(IN_LAVA_RED, IN_LAVA_GREEN, IN_LAVA_BLUE)
#define IN_POWDERED_SNOW_COLOR vec3(IN_SNOW_RED, IN_SNOW_GREEN, IN_SNOW_BLUE)

#define HSV_POSTERIZE_QUALITY vec3(HSV_POSTERIZE_HUE_QUALITY, HSV_POSTERIZE_SATURATION_QUALITY, HSV_POSTERIZE_BRIGHTNESS_QUALITY)
